import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@components/navbar/Navbar";
import { ThemeProvider } from "./ThemeProvider";
import SearchBarNav from "@components/SearchNavBar";
import { SegmentsProvider } from "./SegmentsContext";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
        <Navbar />
        <SearchBarNav />
        <SegmentsProvider>
        {children}
        </SegmentsProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
